#%RAML 1.0 Trait

headers:
  clientId:
    type: string
    required: true
    example: "kjhgf-09876-lkjhgf"
  clientscrect:
    type: string
    required: true
    example: "dfghj-oi7654-lkjhg"
      
      
