#%RAML 1.0 Trait

queryParameters:
  email:
    type: string
    required: true
    example: "abc@gmail.com"
  phonenumber:
    type: string
    required: true
    example: "9063911523"
  phonecountry:
    type: string
    required: true
    example: "+91"
  registrationDate:
    type: string
    required: true
    example: "21-09-2020"
      